### ISSUE TITLE
Undo/Redo text modifications

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#156]
When making changes to the text, whether in any node, or in the notes, and when wanting to go back and undo using the shortcuts only the commands deal with the modifications in canvas and can not  undo/redo modifications in the text itself.

**Comment by phase1geo** [comment]
This was a decision that I made about the undo/redo buffer. Rather than remembering every text edit made for the life cycle of the application, I only remember the undo history for a row that is being edited (i.e., as long as you are editing text, you can undo/redo any changes made to that text). Once you have completed the editing process, the document is saved and the differences between the pre-edited text and the edited text are saved in the undo buffer along with all other row-based changes.  The text undo buffer is then cleared at that point.

This means that text changes can be undone after the row has been changed, but for the entirety of the affected row rather than its parts.

This seemed to make the most sense to me as it pertains to an outlinining application and it reduces the amount of memory required for the undo/redo buffer.

I would potentially be willing to change this behavior, but not at the moment.  If there is a bug in the current implementation, I am willing to get that fixed ASAP.

**Comment by phase1geo** [comment]
Sorry this was a description of what Outliner does :(

You are correct in that text changes cannot be undone while editing the text.  I will change this, but probably in the next release because the body work to support this as well as get Minder's text rendering up to snuff with the work that I'm doing in Outliner is going to take some time.

**Comment by wada3n** [comment]
The idea is beautiful with regard to undoing modifications to the text  as long as you are inside the text and when exit from text, the changes only affect the canvas.
Yesterday I was thinking about a format bar like Outliner for Minder but I feel it will be inserted from another planet in Minder, especially with the sidebar you can add a text formatting tab that has everything related to it.

In the end, I look forward to the changes that you will make in the coming days
good luck

**Comment by phase1geo** [comment]
This feature has been implemented in the devel branch and will be generally available in the next stable release.
