### ISSUE TITLE
Switch GTK variant to dark when switching to dark mode

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Minder#2]
Instead of just switching the map to a dark background, it would be pretty cool to switch the GTK variant to dark as well.

**Comment by phase1geo** [comment]
How do I change the Gtk variant to dark theme?

**Comment by cassidyjames** [comment]
You set [the `gtk_application_prefer_dark_theme` property](https://valadoc.org/gtk+-3.0/Gtk.Settings.gtk_application_prefer_dark_theme.html).

Here's an example from my app, where I bind a switch to that property: https://github.com/cassidyjames/principles/blob/6b44b0432dbc7f8a529da9e7f43617ff04ca93df/src/MainWindow.vala#L58

**Comment by phase1geo** [comment]
I have implemented this change in the master branch. This will be available in the next AppCenter release.

**Comment by nekohayo** [comment]
Hi Trevor, if you would like to consider it, I would propose we reopen this here, as the desktop environments / OSes (including elementary, GNOME, KDE, etc.) underwent a little revolution in 2022 with the new FreeDesktop API for handling light vs dark system/user preferences; i.e. there is finally a standardized way for your app to authoritatively know (without just trying to "guess" whether the current GTK theme is dark or not) what the user's intent is in terms of light/dark themes.

* Overview here: https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
* Implementation tips here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference

I understand that, currently, color schemes in Minder are handled on a per-document level rather than at the app level... however, while I might want to export using either the light or dark color schemes depending on the map, I would like to be able to _edit_ / work with the color scheme inherited from the OS, as the light theme burns my eyes at night, especially since mindmaps tend to have 90% empty space vs textual contents, in terms of pixels usage.

Would you entertain the possibility of the app allowing to decouple the "export color schemes" from the "runtime" (i.e. editing) color schemes? The editing interface canvas could offer the choice between "Inherit from the system (automatic - does not affect export)" and "Use the map's export color scheme", or something like that.

If you would be amenable to the idea, we could either reopen this ticket, or create a new one.
