### ISSUE TITLE
Copy/paste enhancements

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Minder#209]
I am having some related/other issues with copy/paste:

1) I cannot copy nodes from minder to another application... namely gedit. In freemind/freeplane nodes would be pasted one per line and sub nodes would be indented by a tab per sublevel

2) the other way around it works (copying text from gedit to minder) but behavior is not what I expected as it happened in freemind/freeplane, that is, when pasting several lines of text a new sub node should be created for each line; right now just one sub-node is created with all the lines inside

_Originally posted by @daveiro in https://github.com/phase1geo/Minder/issues/206#issuecomment-683840684_

**Comment by phase1geo** [comment]
Neither of these features are currently supported by Minder. Pulling these suggestions into their own issue so that I can track them separately from the other outstanding copy/paste bug.

**Comment by daveiro** [comment]
> Neither of these features are currently supported by Minder. Pulling these suggestions into their own issue so that I can track them separately from the other outstanding copy/paste bug.

oh, ok, thanks for creating a separate issue and informing these features are not yet supported; they are quite useful in the following scenarios (or similar):

1) while away from the PC I quickly create some notes in Joplin app to later add to a mindmap, when opening minder in the PC I just paste the notes content and the branches are automagically created

2) after a brainstorm session with colleagues, I send an e-mail with a bullet list corresponding to the tree I was editing in minder during the meeting

**Comment by phase1geo** [comment]
FYI.

Minder has a feature called Quick Entry which displays a text entry field, allowing you to enter nodes as text which then are inserted into the mind map at the currently selected node (or as a new tree if no node is selected). It’s not as fast as pasting text (obviously); however, it supports tabs in the text to allow you to control the resulting tree rather than only supporting pasting as inserting a number of child nodes.

Additionally, you can export a mind map as plaintext. Difference is that the text is saved to a file and includes notes and checkboxes.

I can still support what you are asking for, but thought I would mention what currently exists in case you were not aware.

**Comment by daveiro** [comment]
I had already tried the quick entry feature but didn't know of the possibility of using tabs for having subtree(s), thanks for that info!

And I also had tried exporting as text file which is a nice workaround for the copy from a Minder map not working directly yet.

I suppose you can reuse the code that implements the quick entry feature to handle/implement the paste into a Minder map and the code implemented for export to plain text to handle/implement the copy of content from a Minder map to the clipboard?

**Comment by phase1geo** [comment]
I have added the text copy/paste enhancements described above in the devel branch which will be generally available in the next stable release.

**Comment by daveiro** [comment]
thanks!!! :+1:

**Comment by daveiro** [comment]
I just bumped into an issue here with copy/paste between minder and other apps; it's frequent for me to keep notes/data in nodes in mind maps (like comments, replies, phone numbers, shopping list items, etc.) and the expected behavior of copy/paste of just one node (or a set of sibling nodes) would simply be the "pure" content is pasted.

But what happens while copy/pasting is that a dash and a space are added before contents while pasting; I suppose this happens from reusing the code of exporting maps to text files?

But I would say that it, in copy/paste between apps, it makes more sense to never include "- " before node contents and just put "pure" contents in the clipboard; and if one is copy/pasting a tree, then at max a tab character is added (one for each level of deepness) for child nodes; does it make sense?
