### ISSUE TITLE
Portuguese words with special characters do not work

### ISSUE THREAD

**Issue by renaldofreire** [phase1geo/Minder#217]
Words with accents in the Portuguese language do not work.

If I try to write directly in Minder the words: _atenção_, _bebê_, _balão_, they are not written with special characters.

If I write the same words in another location, and copy them into Minder, the words are spelled correctly.

**Aur version** 
Last Updated: | 2020-06-24 03:29

**OS**
Arch Linuyx x86_64

**Comment by phase1geo** [comment]
That last updated time stamp looks really out of date. The latest Minder release is 1.10.0 (released a week or so ago). Any chance that you could download from GitHub, build from source, and verify if the issue still persists?

**Comment by renaldofreire** [comment]
Hey @phase1geo. I tested with the github version, the problem persists.

**Comment by phase1geo** [comment]
I am unfamiliar with entering text in non-English languages.  How would I attempt to add these words using an US-English keyboard so that I could attempt to replicate the issue?

**Comment by phase1geo** [comment]
In addition to this last question, does entering text in the "Note" text widget (in the sidebar) work properly?

**Comment by renaldofreire** [comment]
The language and format in my arch linux is in English. The keyboard is in the American (US, alt. Intl.). This error is strange, in other applications everything works normal.

The Quick Entry menu also works correctly:

![minder-print](https://user-images.githubusercontent.com/35435780/92412839-d18c3e80-f123-11ea-9b5b-3f3b943772f3.png)

**Comment by phase1geo** [comment]
It doesn't work in the mindmap area because Minder doesn't use Gtk+ text widgets when editing text in them. Whereas the Notes field in Minder does.  I just need to know what needs to be done to render these texts properly.  The mindmap area does support Input Methods, so I just need to know what isn't working properly.

So what do I need to do to insert special characters for Portuguese using the US International keyboard?

**Comment by phase1geo** [comment]
Okay, I was able to figure out how to insert the special characters now.  I think I know what needs to be done, so I'll give it a shot.

**Comment by daveiro** [comment]
just to say that I am using Fedora 32 system with portuguese keyboard and portuguese keymap; both the official RPM from fedora and github code work fine with me to insert portuguese special characters...

**Comment by phase1geo** [comment]
I have checked in a fix for this issue into the devel branch which will be generally available in the next stable release.  If you get a chance@renaldofreire, could you grab this branch and let me know if the issue is fixed for you?  @daveiro, could you grab this change and let me know if things still work for you?

**Comment by daveiro** [comment]
@phase1geo I just built and installed the latest devel and all is working fine

**Comment by renaldofreire** [comment]
I removed the application folder and used removal commands in my distro (pacman -Rs minder) but the application was not removed. can you help me? There is no removal guide in "README.md ". I need to uninstall to test with the development version.

**Comment by phase1geo** [comment]
Could you grab the development version and unpack it, go into the minder directory and execute './app uninstall'?  You may need meson installed to perform this action (but you'll need that and other packages anyways in order to build the development version).

**Comment by renaldofreire** [comment]
Thank you @phase1geo @daveiro! In the development version it worked perfectly. The application is amazing.
