### ISSUE TITLE
Node image increases size automatically

### ISSUE THREAD

**Issue by renaldofreire** [phase1geo/Minder#219]
Node images increase in size after reopening a project.

1. Add images (svg or png) in a node;
2. Resize image;
3. Save a project in ".minder";
4. Reopen saved project;
5. Image increases size automatically.

System: Arch linux x86_64.
Minder version: devel branch.

![error_1](https://user-images.githubusercontent.com/35435780/92806734-a65a5700-f390-11ea-82bb-6e25c7a80a4d.png)

After reopen:
![error_2](https://user-images.githubusercontent.com/35435780/92806755-aa867480-f390-11ea-8bbf-85db947091f5.png)

**Comment by phase1geo** [comment]
I’m seeing that issue on my end as well. Fix forthcoming...

**Comment by phase1geo** [comment]
This issue should now be fixed in the devel branch which will be generally available in the next stable release.  

To test out the fix, you will need to update, start Minder, resize the incorrect images to their correct size, and exit Minder.  After that, starting the app again should result in the correct image sizes being displayed.

**Comment by renaldofreire** [comment]
The problem was resolved in devel version.
