### ISSUE TITLE
Shortcut  to quickly add notes

### ISSUE THREAD

**Issue by SevereOverfl0w** [phase1geo/Minder#225]
This would be useful, as I go over my mindmap and collect information throughout a conversation.

I've tried Ctrl+Shift+R, but there's no keybinding to submit (e.g. Ctrl-Enter).  A keybinding to open the properties and focus the notes text box would also work well for me.

**Comment by phase1geo** [comment]
I have added the keyboard shortcut <Shift>e which will automatically display the sidebar and make the note field (for both node and connection notes) have keyboard focus for immediate editing. The keyboard shortcut can be used when a node is selected.  The contextual menu text has been altered to "Edit Note" instead of "Add Note"/"Remove Note".

The code has been submitted to the devel branch will will be generally available in the 1.11.1 stable release.

**Comment by SevereOverfl0w** [comment]
Nice, thanks!
