### ISSUE TITLE
Slash and space recognized as link

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#228]
![image](https://user-images.githubusercontent.com/30507409/94529534-88bb3780-0242-11eb-898b-9ebc76b50412.png)
```
someText, / someText
```
second someText is link(even if there a space)

**Comment by phase1geo** [comment]
I added a file path parser in the 1.11.0 release. Since pathnames typically start with a forward slash (on Linux systems) and may have spaces within directories and files, the parser would allow this syntax. However, as you have noted, this means that non-path syntax can be incorrectly detected, I have modified the pathname parser in the devel branch to only detect pathnames if the pathname is preceded by 'file://'.

**Comment by nekohayo** [comment]
It seems this bug has come back for some strange reason, I'm seeing this in 1.11.1 (strangely, I had never encountered it before):

![Screenshot from 2021-05-21 17-27-18](https://user-images.githubusercontent.com/479401/119200093-4016ef80-ba5a-11eb-8a5b-dcd6dba600a0.png)

**Comment by phase1geo** [comment]
I have just released version 1.12.3 which does not exhibit this issue.
