### ISSUE TITLE
When Opening a File With A Theme That Does Not Exist, Minder Crashes

### ISSUE THREAD

**Issue by dCaples** [phase1geo/Minder#232]
First of all, Minder is SOO awesome!! I use it all the time. I found a slight bug, however. When you try to open a mindmap with an invalid theme (like if you created a custom theme and then wanted to open the mind map on another computer which does not have that theme) the application crashes. This can be fixed by going into the mindmap file and changing the line with the theme. Maybe there should be a feature that uses the default theme if the one specified in the mindmap file is not avalible?

**Comment by phase1geo** [comment]
Custom themes used by a mind map are saved into the Minder save file and “travel” with that file. Minder version 1.11.3 should have fixes for application crash due to the use of custom themes. You can try downloading the master branch from GitHub if you want to verify that the application crash is gone in your case.

**Comment by dCaples** [comment]
okay I updated and that was the problem. Thanks!
