### ISSUE TITLE
Inconsistency between ctrl+select and shift+select

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#250]
Currently, if you click a node, then hold shift and click other nodes, it adds/removes the clicked nodes to the selection, which is the behavior that would normally be expected of ctrl+click.

Minder should respect the standard pattern and do:
* Range selections with shift (click/select a node, hold shift and click the first/last node in the range that you want to select)
* Non-contiguous selections with Ctrl (the behavior that is currently assigned to Shift)

**Comment by phase1geo** [comment]
Shift + click was chosen to add/remove selections for two reasons:

1. Control + click on a URL within a node will automatically open a browser.

2. The Shift modifier typically indicates an alternative behavior to the same key/click without the shift modifier.  Clicking on a node selects it, always. Shift + click allows you to deselect a node in addition to adding to the selection.  I realize that some tools use Shift + click to mean "select a range" of sequential things.  However, since a mind-map is a tree, there really isn't a concept of "sequential". Does sequential pertain to breadth-first things or depth-first things or none of the above?  I feel that this gives Minder some flexibility to define its own behavior in this area, even if other mind-mapping applications do something different.

**Comment by daveiro** [comment]
Hi there @phase1geo: as you might remember I was raising this same issue in summer and, just like @nekohayo, I would guess the majority of users of Minder would prefer to have the "standard pattern" in most apps. What you mention about the Shift modifier is, I would say, a "less common standard" than the general standard of using shift to select a range of things and ctrl to select things in a non contiguous way. Regarding opening links, I would suggest that you use a different key to open links in a node (like Alt) or follow the same functionality found in Freemind/freeplane: having a special icon in the beggining of the node, which when clicked, triggers opening the link - this icon could "appear" only while hovering the node with the cursor, in a similar manner to links in a google doc.
