### ISSUE TITLE
Alt+up/down/left/right shortcuts to move (reorder or reparent) selected nodes

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#254]
I would like the equivalent of the shortcut to reorder paragraphs in text editors like Gedit (GNOME's default text editor), in Minder.

That is, in a vertical list, Alt + arrow keys would move the selected nodes either across within a branch of siblings (easily reordering them without touching the mouse), or up/down the tree hierarchy, but that one might be tricky to do because how do you know where to make it go down in the hierarchy... so I would be happy even with just reordering within siblings of the same level. Which arrow keys are used would depend on the node layout, I guess.

**Comment by phase1geo** [comment]
I have added this feature in the devel branch which will be generally available in the next stable release.

**Comment by phase1geo** [comment]
Assuming that the layout is a right direction layout (children are to the right of their parent). If the user uses the Alt-Left shortcut, would you expect the parent and the child nodes to swap places or would you expect the child (and its descendants) to be joined to the parent of the parent (i.e., become a sibling of the parent node)?

**Comment by daveiro** [comment]
This is a great feature that I had in mind to request as an enhacement too. Thanks for implementing it! I just downloaded and installed the latest devel branch and Alt+up and down works nicely with just one node selected, but it would be super that it works with more than one node selected. Regarding your question of using Alt+left I would say that the expected behaviour would not be to swap places, but the child and its descendants join the parent of the parent, just like when while editing a bullet list in word and we select a few child items of the list to be "promoted in the tree" they become siblings of their previous parent. Regarding Alt+right I would say that there are too many possibilties and none is obvious, so better leave it out.

**Comment by phase1geo** [comment]
Makes sense to me.

**Comment by phase1geo** [comment]
I have submitted a change to the devel branch that adds support for Alt+direction (when direction is towards the selected node's parent) causing child nodes to be moved to the parent's parent.  This change will be generally available in the next stable release.
