### ISSUE TITLE
Don't export BMP by default, automatically remember last used export format

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#258]
When using the export dialog, it is annoying to have to select the export format every time, when I want to use the same format across iterations 99% of the time. Currently the export dialog defaults to BMP* everytime I use it. Minder should remember what I used the last time.

*: while we're here, I posit that BMP is a 100% useless legacy format to even have in the choices there. PNG has been supported on pretty much every device from the last 16 to 24 years. If you're going to have a lossless raster image format by default, I'd say it should be PNG (with transparency), which, as far as I know, is superior in every respect.

**Comment by phase1geo** [comment]
Technically, there isn’t a default type. They export drop down is just a list of supported export formats listed in alphabetical order. I don’t know if I can specify to a default filter to use when creating the export dialog. I’ll look into it.

**Comment by phase1geo** [comment]
I looked into the issue yesterday and was unable to get the Gtk file chooser to switch to a different default.  Looking at the Gtk source code, I'm not seeing any support for this feature either.

I have had a long-standing feature request to enhance the export process via GUI.  Rather than just use essentially a "Save" dialog window, use a more sophisticated dialog window that would allow you to now only select an export type by configure some export options for the selected type.  Since this dialog wouldn't depend on a native file system interface, I could make the widgets behave however I want them to.  This feature would take care of this enhancement request.

**Comment by nekohayo** [comment]
> I looked into the issue yesterday and was unable to get the Gtk file chooser to switch to a different default. [...]

Hmm, could it be simply the act of filtering with something that matches one of the offered filters in the UI? Something roughly like https://gitlab.gnome.org/GNOME/pitivi/-/blob/master/pitivi/medialibrary.py#L793 in spirit, i.e. you tell the FileChooser to filter for "*.png" (maybe with the GtkFileChooser's "set_filter" method instead) and if that matches one of the filters you had in your combobox it will set the combobox to that? From the gtk_file_chooser_set_filter description in GTK's docs:

> Sets the current filter; only the files that pass the filter will be displayed. If the user-selectable list of filters is non-empty, then the filter should be one of the filters in that list. [...]

**Comment by phase1geo** [comment]
Yes, that it was I tried, but it didn't work.

**Comment by phase1geo** [comment]
I have modified the export UI to give Minder more control over default values.  It also allows us to add export options for each export type (currently options only exist for PNG and JPEG output formats).  I have also removed support for BMP export.

The code has been checked into the devel branch which will be generally available in the next stable release.
