### ISSUE TITLE
Screenshot image inserts are too small and fuzzy

### ISSUE THREAD

**Issue by dfarmilant** [phase1geo/Minder#279]
I'm creating a mind map for my Real Analysis course, with branches such as definitions, theorems, etc. (Focus mode is particularly helpful when making connections, awesome feature). As far as I can see, there is no LaTeX integration, which would be my first formatting choice, as I could rewrite definitions, etc. However, it's faster to just use screenshots from the PDF of the course text and insert them. Unfortunately, the image is too small to be of any use.

Attached is a .png of the screenshot I wanted to include and what it looks like when it is included.

![Screenshot from 2021-01-23 15-53-51](https://user-images.githubusercontent.com/59981274/105615735-6f616c80-5d98-11eb-97b5-c3df14ed529c.png)

![Screenshot from 2021-01-23 16-29-03](https://user-images.githubusercontent.com/59981274/105615737-6ffa0300-5d98-11eb-88e4-773cb64acbdf.png)

**Comment by phase1geo** [comment]
I don't know what I can do about this without negatively effecting tool performance.  I intentionally scale any image to no larger than 300x300 pixels in size.  If either the height or width of the image exceeds this size limitation, the image is scaled to fit within that size.  This keeps redraw times down low enough to make things feel fluid when using the application.

Yout should be able to view the original image by going to the sidebar and clicking on the image link.

Adding support for drawing formulas is on the list of features to add for the application.

**Comment by phase1geo** [comment]
I've looked into this issue, and I think I know why you are seeing a fuzzy image and how you would deal with this within Minder.

When an image is attached to a node, the image is scaled to be no larger than the standard width of the node (which can be modified within preferences).  The default is typically something like 200-250 pixels.  Scaling down will have the effect of making the image less readable due to bilinear scaling rules.

However, you can adjust the width of the image to any size that you want by selecting the node and dragging the square in the upper right-hand corner of the node to the left or right.  Simply adjust the width of the node until your text looks more crisp and you should be good to go.
