### ISSUE TITLE
Save on close modal

### ISSUE THREAD

**Issue by hnariman** [phase1geo/Minder#360]
Minder crashes if closed with unsaved data. 
my fix is go and remove ~/.local/share/minder/unnamed**, but this is not expected behavior and this happens if closed without saving. 

My suggestion is to add some modal menu to save before closing. (which all we got used to) and at least this will prevent from accidental closing and also will prevent some crashes maybe.

PS. I would love to contribute, but not familiar with Vala and currently very tight on time to dig into.
BTW: Great job! Great project! I hope to get hands on and participate more, maybe on bug fixes, ASAP.

**Comment by phase1geo** [comment]
The problem isn't with unsaved files. Minder aves all changes made under the hood. When Minder is closed all data is saved.

There is currently a known issue with newer valac compilers on some distros that is generating bad code that is leading to crashes. The fix is non-trivial and should be unnecessary. Unfortunately, lots of different distros are building bad packages of Minder (or aren't even building from the latest release), so it is difficult for me to address the issues.

**Comment by phase1geo** [comment]
What OS/distribution are you running?

**Comment by EtianeZauMarcelino** [comment]
Minder crashes on Linux Mint 20.1 Cinnamon...

**Comment by ravindrapankaj** [comment]
Minder crashing on fedora 33 as well.

**Comment by lufticus** [comment]
> Minder crashes on fedora 33 as well. When I tried to run it on the terminal, it spits out the following:
> I/O warning : failed to load external entity ~/.local/share/minder/favorites.xml
> I/O warning : failed to load external entity ~/.local/share/minder/exports.xml
> free(): invalid pointer
> [1] 6429 IOT instruction (core dumped) com.github.phase1geo.minder

Same on my LMDE 4

**Comment by phase1geo** [comment]
Can someone confirm/deny that this bug still exists with the 1.12.4 stable release?

**Comment by lufticus** [comment]
New installed via LMDE package manager - no problems any more! THX!
