### ISSUE TITLE
[feature request] macos support

### ISSUE THREAD

**Issue by DumbGameMaker** [phase1geo/Minder#406]

**Comment by phase1geo** [comment]
If macOS supported Flatpak this would be feasible.

**Comment by prokoudine** [comment]
@DumbGameMaker 

While low-level dependencies like glib and GTK (and even Vala) are definitely available on macOS, Trevor would have to spend quite a bit of time building higher-level dependencies like libgranite and then setting up either paid CI at CircleCI to produce builds or buy Apple hardware which is not necessarily his choice :) Oh, and the annual Apple Developer subscription and the whole notarization thing... Better leave all that to a new interested contributor and focus on actual features and bugs perhaps?

**Comment by phase1geo** [comment]
If you are just looking for a comparable mind mapping app for macOS, MindNode works similarly to Minder.

Unfortunately, if you are just looking for Minder to work on a Mac because you want to use Minder for cross-platform uses, I don't see that happening. I do not want to rewrite the app and I think that getting it to work as is won't be feasible.

**Comment by DumbGameMaker** [comment]
> @DumbGameMaker
> 
> While low-level dependencies like glib and GTK (and even Vala) are definitely available on macOS, Trevor would have to spend quite a bit of time building higher-level dependencies like libgranite and then setting up either paid CI at CircleCI to produce builds or buy Apple hardware which is not necessarily his choice :) Oh, and the annual Apple Developer subscription and the whole notarization thing... Better leave all that to a new interested contributor and focus on actual features and bugs perhaps?

you dont need the developer subscription and notarization to develop for macos

**Comment by DumbGameMaker** [comment]
> > @DumbGameMaker
> > While low-level dependencies like glib and GTK (and even Vala) are definitely available on macOS, Trevor would have to spend quite a bit of time building higher-level dependencies like libgranite and then setting up either paid CI at CircleCI to produce builds or buy Apple hardware which is not necessarily his choice :) Oh, and the annual Apple Developer subscription and the whole notarization thing... Better leave all that to a new interested contributor and focus on actual features and bugs perhaps?
> 
> you dont need the developer subscription and notarization to develop for macos

k, ill check it out

**Comment by prokoudine** [comment]
> you dont need the developer subscription and notarization to develop for macos

If the idea is to develop an app that every other user will be complaining about, then sure, you don't need either of those.

We've been there with GIMP. I spent probably an hour every week just answering again and again the same question how to run the program (because of the warning messages). Then it was signed and notarized and we never looked back.
