### ISSUE TITLE
Flatpak and distro repository version missing text? 

### ISSUE THREAD

**Issue by Leyeev** [phase1geo/Minder#411]
Hello, I was using the Flatpak version and I have found out the my distro (Debian) has this app in their repository so I made the switch but when i open my minder it shows no text but it maintains the mind maps layout. Is this normal? the only thing workaround i can find is exporting all my mind in plain text and importing them. 

![image](https://user-images.githubusercontent.com/69566085/132846451-cb85dd1c-319d-4728-a6b9-cbbeee5ec056.png)

BTW, Thank you for this wonderful app

**Comment by phase1geo** [comment]
That’s not normal. Can you get the version number? In a terminal, enter:

`com.github.phase1geo.minder —version`

**Comment by phase1geo** [comment]
That’s a double dash, not an emdash.

**Comment by phase1geo** [comment]
Unfortunately, in this case, I believe the version of Minder you have didn’t save correctly, meaning that your .minder file is missing the text that it should otherwise have. The latest version is 1.13.1. The best Flatpak is the one from the elementary repository as it uses versions of the valac compilers that doesn’t have the same memory handling issues as the gnome Flatpak which most likely lead to your problem of missing text in the first place.

**Comment by Leyeev** [comment]
> That’s not normal. Can you get the version number? In a terminal, enter:
> 
> `com.github.phase1geo.minder —version`
1.9.2



> Unfortunately, in this case, I believe the version of Minder you have didn’t save correctly, meaning that your .minder file is missing the text that it should otherwise have. The latest version is 1.13.1. The best Flatpak is the one from the elementary repository as it uses versions of the valac compilers that doesn’t have the same memory handling issues as the gnome Flatpak which most likely lead to your problem of missing text in the first place.

I have used a flatpak version on a another device to open a save file from the gnome version and it work correctly. I will probably used to the flatpak onwards. Thanks
