### ISSUE TITLE
Adding missing functionality when editing text entries

### ISSUE THREAD

**Issue by megatux** [phase1geo/Minder#43]
The "edit textbox" control does not support the usual moving between words with Ctrl-[left/right], Home/End keys, text selections, etc that are present in normal GTK+ edit boxes. Looks like a custom widget without all the expected text-edit functionality (except paste AFAICS).

**Comment by phase1geo** [comment]
I have added the following editing features when editing text in the mind-map itself. If there are any more that you would like to see, add it to this bug report:

- Left, Right, Up, Down: Moves the cursor in the given direction (clears the selection if it exists).
- Control-Return:  Adds a newline to the text.
- Control-Tab: Adds a tab to the text.
- Control-Right: Moves the cursor to the next word.
- Control-Left: Moves the cursor to the previous word.
- Control-Up: Moves the cursor to the beginning of the text.
- Control-Down: Moves the cursor to the end of the text.
- Control-Shift-Right: Adds/Removes the next word to/from the current selection.
- Control-Shift-Left: Adds/Removes the previous word to/from the current selection.
- Control-Shift-Up: Adds/Removes all characters from the cursor to the beginning of the text to/from the selection.
- Control-Shift-Down: Adds/Removes all characters from the cursor to the end of the text to/from the selection.
- Control-/: Selects all text.
- Control-\: Deselects all text.
- Shift-Right: Adds/Removes the next character to/from the selection.
- Shift-Left: Adds/Removes the previous character to/from the selection.
- Shift-Up: Adds/Removes the previous line to/from the selection.
- Shift-Down: Adds/Removes the next line to/from the selection.
- Control-x: Cuts the currently selected text and adds it to the clipboard.
- Control-c: Copies the currently selected text to the clipboard.
- Control-v: Pastes the clipboard contents into the text (if text is selected, replaces the selected text); otherwise, pastes at the cursor position.

For mouse control, I have the following functionality already available:

- Click and drag: Selects all text from the clicked character to the current mouse cursor position.
- Click: Positions the cursor at the clicked position
- Double-click: Selects the current word.
- Triple-click: Selects all text.

I am adding the following:

- Shift-click: Adds/Removes all text from the anchored selection point to the mouse cursor position.
- Shift-Double-click: Adds/Removes all text from the anchored selection point to the end/beginning of the word at the mouse cursor position.
