### ISSUE TITLE
More styling for node text

### ISSUE THREAD

**Issue by 04ELY** [phase1geo/Minder#437]
Can we do striketrough (~~) ?
We can do 
- bold, "**" and "__"
- italics, "*" and "_"
- code, "`"
and urls.

Couldn't find on wiki.
I've looked at FormattedText and MarkdownParser but couldn't wrap my head around it yet :sweat_smile:  Not sure if I'm looking at correct ones anyway :smiling_face_with_tear:

**Comment by phase1geo** [comment]
I have added strikethrough parsing support in node titles in the master branch. Unfortunately, strikethrough parsing support is lacking in the node note field since I'm using the gtksourceview-4 Markdown parser which currently lacks support for this syntax. I don't know what I can do about that for now.
