### ISSUE TITLE
Theme does not change

### ISSUE THREAD

**Issue by sonovice** [phase1geo/Minder#465]
I have just installed Minder for the first time via flatpak. Changing the theme in the preferences has no effect, even after a restart:
![image](https://user-images.githubusercontent.com/8217108/158991414-9e7759cf-cda5-4057-976e-3b240d6bcd58.png)

**Comment by phase1geo** [comment]
Changing the default theme in preferences isn't designed to change the themes of any mindmap that already exists. It is meant to set the theme of any newly created mindmap to that default theme.

To change the theme of an existing mindmap, open it, go to the "Map" sidebar pane, and select a theme from the list there.

**Comment by sonovice** [comment]
Ah, thank you for the clarification. I did not see the per-file theme prefs in the sidebar. Is there anything I can do about the purple head bar to have it better fitting to my default GTK dark theme?

**Comment by phase1geo** [comment]
Unfortunately for you, not without some code modifications on my part.  Minder is designed to be an elementary OS native application which encourages the use of color in header bars.

**Comment by sonovice** [comment]
Alright, thank you very much for the response.

**Comment by healingdrawing** [comment]
dude, think about fix this if possible, the dark theme changing on the fly.

Because i gave to your nice app x3 stars after could not change the style on the fly. After i discovered github issues (i was ready to create new issue) i found explanation that the theme will be changed for the new document only. And cant edit my review on software page, and can't write new one(server request fails in some purposes)  😐

**Comment by phase1geo** [comment]
The theme request in this issue is not something to fix, it is the way that the application is intended to work.
