### ISSUE TITLE
Enchant Link (url) color in Dark / Solarized Dark themes

### ISSUE THREAD

**Issue by VasoVV** [phase1geo/Minder#507]
The blue colour of the text with links is almost unreadable in the Dark / Solarized Dark themes.

Could you please change it to a more contrasting one?
Also, it would be perfect to change the toxic-blue colour of the links in the light themes to some colour that rests the eyes (e.g. #3078E9)

Thank you!

**Comment by phase1geo** [comment]
I could always modify colors for the built-in themes; however, since colors are always fickle and hard to please everyone, Minder actually comes with the ability to create new themes (based on existing themes).

You can change the foreground and background colors of pretty much everything, including links.  I would suggest using this feature to get what you need.  If you haven't used it, simply go to the Map sidebar tab, select an existing theme and then click the (+) plus button at the bottom of the sidebar.  You can change the colors here, give the new theme a name, and click the Save button to create it.  The new theme will be added to the existing list of themes.  If you create a mindmap and apply the custom theme, the theme will be saved to the .minder file so that if you open it somwhere else within Minder, the theme will be copied to that instance of Minder and still be usable by the same mindmap file.

**Comment by VasoVV** [comment]
Oh, great! I did not suspect such functionality.

But to tell you the truth, I wouldn't look for those theme settings if the default themes had not such color awkwardness.
I guess that default themes have not to be absolutely perfect but as usable as possible.
In this case, only the links' color has a problem, all others are good, IMHO.
I've found that `url_foreground="#62a0ea"` looks good for both light and dark themes. You could set it as default.

Thank you!

**Comment by phase1geo** [comment]
I can make the color change to the defaults. I just wanted to mention the theming feature to allow you to more quickly fix the issue on your end.

**Comment by phase1geo** [comment]
I'm noticing a related bug where changing the theme isn't updating the colors used in rendering fonts.  I'll need to get this issue fixed before I can consider this issue complete.  I have updated the URL link default color for the solarized themes to the suggested color.

**Comment by phase1geo** [comment]
Okay.  I have fixed the text coloring update bug when themes are changed.  I have modified the SolarizedLight, SolarizedDark and Dark themes with the suggested URL foreground color.  Fixes are in the master branch.
