### ISSUE TITLE
Export / Import in Mermaid format

### ISSUE THREAD

**Issue by stefano-b** [phase1geo/Minder#51]
Mermaid is a markdown-like scripting language aimed at generating charts.

Quoting from the [website](https://mermaidjs.github.io/):

> Generation of diagrams and flowcharts from text in a similar manner as markdown.
> 
> Ever wanted to simplify documentation and avoid heavy tools like Visio when explaining your code?
> 
> This is why mermaid was born, a simple markdown-like script language for generating charts from text via javascript.

The implementation for [flowcharts](https://mermaidjs.github.io/flowchart.html) in particular seems to be a 
great option to import/export mindmaps into Minder.

**Comment by phase1geo** [comment]
Sounds like a great idea. I’ll look into it.

**Comment by phase1geo** [comment]
I have added a Mermaid export function which will be available in the next release of Minder. I will add an import capability to the todo list for following release.

**Comment by phase1geo** [comment]
In regards to importing Mermaid files into Minder, do you have any suggestions on how to parse this format into something that Minder can more easily handle? I could always attempt to write my own parser, but I’m curious to know if there is a better option.

**Comment by phase1geo** [comment]
After further review, I have decided not to add Mermaid import support. There are two reasons driving this decision. First, writing the Mermaid parser in Vala is not a trivial, straightforward task. Second (and more importantly), the closest Mermaid document to a mind-map is a flowchart which may or may not follow standard a typical mind-map structure. Though converting a mind-map to a flowchart is a simple, straightforward process that does not require human interaction, the same is not true to convert in the opposite direction.

Since Mermaid export support currently exists, I am closing this issue.
