### ISSUE TITLE
Manual positioning information should still be saved into the file format

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#554]
## Historical context

Citing https://github.com/phase1geo/Minder/issues/553#issuecomment-1599593700 :

> The canvas "origin" and zoom level information has been moved to the ~/.local/share/minder/tab_state.xml file now. You can clear this issue up by either doing what you did or deleting this file. This file is used by Minder to remember the state of the tabs between Minder sessions, so you will only force Minder to forget that by deleting this file.

I suspect this was done to solve issue #503 (and maybe #341 too), which makes sense on paper... _except_ under one situation: **manual positioning.**

## Symptoms

With 1.15.2 on Fedora 38, to work around the autopositioning bugs of 1.15.x and also to have a custom compact layout for my mind map by manually positioning each node, I have done manual positioning of every node in one particular mindmap.

However, when I synchronize that .minder file and open it on another computer (with the same software versions), it opens it in automatic layout mode, with all nodes folded (not remembering which ones were left unfolded or not), and having lost the positioning.

## Proposed approach

Overall this shouldn't happen; if the user has taken the care to manually position everything, it should be considered user data within the minder file and open identically on any machine.

Even if the user then switches to auto layout, it's probably good to preserve the previously set manual values so that they can losslessly go back to manual layout if the layout mode change was a mistake or temporary decision.

That said, the values could be rounded at least to integers to avoid micro-shifts like what was seen in issue #503...

**Comment by phase1geo** [comment]
The .minder file is not completely void of positioning information, so the positioning information for manual layout should still be in place in the .minder file.  Perhaps there is a bug that is causing this positioning information to be unused, but I will have to check on that.

**Comment by phase1geo** [comment]
I attempted to test this out using Minder version 1.15.5 (latest version available) and am not seeing the described behavior.

Here's what I'm doing.
- Create mindmap with manual layout
- Save the mindmap to the file system
- Exit the application

If I restart the application, the mindmap opens up without any changes to the layout.  Everything looks exactly the same as it did before the application exit.

Afterwards (to simulate to the best of my ability), I delete the ~/.local/share/minder directory (this contains all opened tabs and positional information for each tab).  I then restart Minder, open the saved mindmap and things still look good (manually positioned nodes in the right place, etc.).

Could you verify that the problem still exists with 1.15.5?  There were several bugs fixed with the zoom and positional data in that version.
