### ISSUE TITLE
my map disappeared

### ISSUE THREAD

**Issue by antonio24073** [phase1geo/Minder#555]
Hi,

I clicked with alt and moved with the mouse and it disappeared. And pressed a lot of times in the zoom to try fix. 
It went to somewhere in the infinite kkkkk 

Best regards.

**Comment by Bella42** [comment]
Hi,
I have the same problem. I know that my mindmap is still there because I can export it, e.g. as png, but I am unable to navigate to it. Therefore, I cannot edit it or use it in any way.

So far, I tried to find my map by:
- moving around
- zooming in and out
- searching for words  I know exist on the map in the hopes that selecting one of the results would focus on the specific node. The search works but no refocus on the map.
- adding a new node
- changing themes

Do you have any ideas on how to find the map? FYI, I have a map with several root nodes but it seems to be a problem with one root node as well.
It would be a pity if this continued because I really enjoy Minder.
Thanks for your work!

**Comment by phase1geo** [comment]
I am working on some changes to fix this issue, but they are not complete at this time. If you are using version 1.15.0 or later, you should be able to make things better by deleting the ~/.local/share/minder/tab_state.xml file and restarting Minder. Just keep in mind that deleting this file will lose the current tab state, so make sure that you save any maps in tabs before doing this.

**Comment by antonio24073** [comment]
I saved the map and opened again and it fixed. I don't know if it's lucky.

**Comment by Bella42** [comment]
@phase1geo Thank you for looking into it. I am using version 1.15.1-1. I already deleted the tab_state.xml. I also had a look at the xml files (the .minder and the tab_state.xml) directly but could not figure out a way to reset the view. The origin-x/-y always seems to be 0 in the tab_state, regardless of what I do on the map. For now, I will let it rest. Maybe I will have time to look into it in a couple of days.

@antonio24073 Unfortunately, this did not work for me, but I appreciate the tip!

**Comment by metal3d** [comment]
In addition, the zoom shortcut is very bad since the latest version. CTRL+mouse wheel is faster than the Flash and we lose the map. That's a pity because minder is very impressive and better than a lot of others mind map applications.

I, for now, use the zoom buttons in the menu instead...

BTW: thanks a lot for minder

**Comment by didier33170** [comment]
A very promising tool ... but same problem as above on Linux Mint 21.1: I zoomed out a large map and it went out of the screen. Since then I have been unable to re-frame it. It happened several time so that **the application becoming impossible to use**.

**Comment by goldanorak** [comment]
ah ah I too have just realized that this "bug" of mindmaps that don't display anything when you open them (omg) ... are in fact badly centered mindmaps. What a relief : it's just a centering bug. The best trick (for now) is to zoom out and move the view back to the right place (?) (version 1.15.1)

**Comment by phase1geo** [comment]
This issue should now be fixed in the master branch now.
