### ISSUE TITLE
Adding new stickers

### ISSUE THREAD

**Issue by Jonas-fr** [phase1geo/Minder#556]
Firstly I'd like to thank you for this simple yet very effective tool which is Minder. It's clean, straight to the point and it just works ; a good example of the KISS philosophy.

There's a page in the wiki showing how to add stickers to an existing mindmap [https://github.com/phase1geo/Minder/wiki/Adding-Stickers]. I'd like to know whether you'd think it will be possible for anyone to add new stickers to the current list of available stickers.

The goal would be to expand the list of available stickers to include new ones for covering all use cases.

Thanks!

**Comment by phase1geo** [comment]
Absolutely! Adding more stickers to cover more cases would be very welcomed.

**Comment by Jonas-fr** [comment]
I'm happy if you agree with this idea. What do you think would be a right course of action for this?
I was thinking about a "stickers" directory scanned upon launching Minder (and/or upon pushing a "scan sticker directory" button) with subdirectories for each categories. Each sticker being a small vector drawing (SVG) in a square canvas. This way anyone could easily expand the list of stickers easily without any code modification. What do you think of that?

**Comment by phase1geo** [comment]
I have updated the main branch to add support for this feature.  Here is a high-level description of the feature usage.

To add custom stickers:
- Go to the Sticker tab in the sidebar.
- If you have one or more sticker image files to add to an existing sticker category, you can just click on the "+" button at the end of the category sticker list and choose the sticker(s) from the open file browser.
- If you want to create your own categories or just have more control over the custom icons, scroll to the bottom of the icon browser in Minder and click on the button at the bottom to display Minder's custom sticker directory in a file browser.  There is a README.md in that directory that describes the details on how the directory structure is setup.

To delete custom stickers:
- Right click on a custom sticker and select the "Remove Custom Sticker" option.
- Bring up the custom sticker directory as described above and delete them using your file browser.

At the moment, if custom stickers are used by mindmaps and those stickers are removed, Minder will effectively crash.  I will get those issues fixed in the next few days.

**Comment by Jonas-fr** [comment]
Thank you for your time. This is a simple yet very powerful addition to Minder which greatly improves it's usefulness!

**Comment by Jonas-fr** [comment]
Nice enhancement
