### ISSUE TITLE
The program crashes when hovering over the notes icon

### ISSUE THREAD

**Issue by gmg137** [phase1geo/Minder#621]
system: openSUSE Tumbleweed
desktop: gnome46

Reproduced:
Hovering over the note icon after adding a note message.

Error info:
> Segment error (core dumped)

**Comment by phase1geo** [comment]
Which version of Minder are you using?

**Comment by gmg137** [comment]
1.15.2 and 1.16.4，Both have that problem.

**Comment by phase1geo** [comment]
I think the problem is that the libmarkdown library that your distribution is using is incompatible with the version that Minder knows how to interact with. I'll look into a fix or at least a workaround shortly.

**Comment by FritzFranuz** [comment]
I have the same Problem, hovering over notes icon on nodes or lines closes the program. same problem occurs hovering over an arrow in the node (after inserting a line). 
I'm using two different lenovo thinkpads with manjaro xfce, minder 1.16.4-1. libmarkdown library is a part of discount, downgrading discount causes minder not to start at all. 
How can I fix this?

**Comment by phase1geo** [comment]
I have implemented a work-around for systems that are using a version 3 of libmarkdown (from within Discourse versions >= 3.0).  Unfortunately, I cannot come up with a solution that will generate HTML from Markdown for systems that use these bleeding edge versions of Discourse.  You should notice that when the cursor is hovering over a node note, any embedded markdown syntax will be displayed rather than have the Markdown be rendered.  Not ideal, but it's good enough for now and eliminates application crashing caused by this problem.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
