### ISSUE TITLE
Features suggestions

### ISSUE THREAD

**Issue by hubitor** [phase1geo/Minder#65]
I would like to suggest some features which I basically miss from other mind mapping software:

1. Import mind maps from other tools such as Freemind / Freeplane
2. Sort node children
3. Add icons to node
4. Add link(s) to node
5. Create nodes from clipboard (respecting tabs like in Freeplane)
6. Shrink/Expand node pane
7. Choose location of node pane (e.g. bottom, right)
8. Note pane better suited for code (e.g. slide bars, fonts, bold, colors, syntax highlighting)
9. Add subtitle to node
10. Modify node color, font

**Comment by phase1geo** [comment]
I modified the original feature request to add numbering so that I can ask some questions about each feature a bit easier.

1, 2, 3, 4 - I understand the feature requests and I believe that I will eventually have support for these requests.

5 - With the 1.3 version of Minder, I have improved copy/paste support between and within Minder windows; however, I’m assuming the feature request is to basically type a number of items in a text editor of some sort such that each item is separated by either a new line or tab character and then when this text is copied to the clipboard and pasted inside of Minder, each item is pasted as a separate node. Is this a correct understanding of the request?

6, 7 - I’m not sure that I will change the inspector panel UI from its current method of display; however, I can understand that if you are entering something like code in the node note field, it might be nice to be able to change the width of the sidebar. I’ll give this some thought.

8 - I will definitely add scrolling support for the note fields (that is honestly just an oversight on my part). As for the other markup requests, I’ll most likely add support for this in the future.

9 - Not sure if I will add this level of detail to the node display. You can always add the idea of a subtitle to the note and see this information with the note tooltip or you could add some new lines to the title itself and place the subtitle text in italics using HTML markup to make it stand out. Perhaps I’m missing something here.

10. You can already change the node font via the Style inspector. You can also already change the node color in the Node inspector (the node color takes on the color of its link to its parent). Perhaps there is something more to this request?

Thanks for your input and feedback.  It is greatly appreciated!

**Comment by hubitor** [comment]
> 5 - With the 1.3 version of Minder, I have improved copy/paste support between and within Minder windows; however, I’m assuming the feature request is to basically type a number of items in a text editor of some sort such that each item is separated by either a new line or tab character and then when this text is copied to the clipboard and pasted inside of Minder, each item is pasted as a separate node. Is this a correct understanding of the request?

Yes! For example if I copy this from my text editor into Freeplane:
```
node 1
node 2
    subnode 2.1
    subnode 2.2
node 3
node 4
    subnode 4.1
    subnode 4.2
    subnode 4.3
```
Freeplane will create the nodes and the subnodes in this structure.
Very useful...

> 9 - Not sure if I will add this level of detail to the node display. You can always add the idea of a subtitle to the note and see this information with the note tooltip or you could add some new lines to the title itself and place the subtitle text in italics using HTML markup to make it stand out. Perhaps I’m missing something here.

This is what I mean:
![Freeplane_Example](https://user-images.githubusercontent.com/6114541/58113070-11f53f80-7bf5-11e9-8102-7290eff52bc2.png)

I find it also very useful.

> 10. You can already change the node font via the Style inspector. You can also already change the node color in the Node inspector (the node color takes on the color of its link to its parent). Perhaps there is something more to this request?

Maybe I'm blind but I can't find any "Style inspector".

Thanks for Minder and your response!

**Comment by phase1geo** [comment]
I’m not sure what version of Minder you have, but as of 1.2.1 you can stylize nodes and links by clicking on the upper right most button (which reveals the inspector) and select the Style tab.

**Comment by hubitor** [comment]
Indeed, I had an older version. Now I see it. Awesome! Thanks!

**Comment by gibranlp** [comment]
I have a suggestion, i can see that the text always wraps to a default node size when a node some text, example:

If i write something large 

Lorem Ipsum is simply dummy 
text of the printing and typesetting 
industry. Lorem Ipsum has been 
the industry's standard dummy
text ever since the 1500s, 

The node wraps and displays something like above, i can make the node larger to display the text only in 2 lines or 1, but when i close the file and open again the text is wrapped again and sometimes the maps ovelap, and i have to resize lots of nodes over and over.

**Comment by phase1geo** [comment]
I have added support for 1, 2, 5, 6, and 9 from the original list in the 1.5.0 stable release. I'm going to close this issue out and create new feature requests for 3, 4, 7 and 8 so that I can track those separately.
