### ISSUE TITLE
Insert text for node link

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#81]
Currently, you can add text to "connection" but not link between child node and parent node. In my opinion, link between child and parent should be able to be named. This is very common in mindmapping.

**Comment by phase1geo** [comment]
I will consider it. Adding text to connections makes sense because without it it is unclear why two nodes are related to each other. On the other hand, node links have an inherent parent-child relationship, making text generally unnecessary.

With that said, I’m sure there are cases where it would be nice to add this information so I will put it on the feature list.

**Comment by Fatih20** [comment]
![Screenshot from 2019-08-02 20 36 50](https://user-images.githubusercontent.com/51940383/62374265-cd2b4480-b565-11e9-91a1-a45a04fe917f.png)
There are many cases to use this. In this example I'm making a mind map about perfect tenses. I need to explain the definition, use, and form. Normally, if I'm making a mindmap on paper, I wouldn't need to draw the shapes with "Definition" or "Form" on them, I'll just draw them along the lines leading to the actual explanation.
There's a workaround like I've put there by making and extra node in between but this just clutters the mindmap.

Here's how it should be :
![Text on Child-Parents](https://user-images.githubusercontent.com/51940383/62375591-db2e9480-b568-11e9-83fe-58ec2ec5e265.png)

**Comment by phase1geo** [comment]
I have decided that I do not want to implement this feature in Minder.  Closing this issue.
