### ISSUE TITLE
Change the theme selection layour and image

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#98]
![Minder Themes](https://user-images.githubusercontent.com/51940383/64546350-b04c1300-d354-11e9-8450-dd3916a86bf8.png)
This looks more elegant and less "tacky". Also, I didn't found any files containing the images that are used to represent the theme. Where are they?

**Comment by phase1geo** [comment]
I agree. This looks much nicer. The “icons” are actually created dynamically by the theme class itself. This is nice because as of 1.5.0 user’s can created their own custom themes.

**Comment by phase1geo** [comment]
I have submitted a change to the development branch that changes the display of the theme icon to match something closer to what you are showing.  Because the theme icon is now a perfect square, I took advantage of this form factor in the sidebar and changed the icon layout to use a grid instead of a vertical box. This allows us to show more themes and makes the new theme create button more quickly visible (both of which are very useful since version 1.5.0 allows users to create and select custom themes).

**Comment by phase1geo** [comment]
Release 1.6.0 has been released with this change.

**Comment by Fatih20** [comment]
Have a screenshot of it?

**Comment by phase1geo** [comment]
It's in the data/screenshots/screenshot-map-properties.png image
